export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_COUNT_PRODUCT = 'UPDATE_COUNT_PRODUCT';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const GET_CATALOG_DATA_BEGGIN = 'GET_CATALOG_DATA_BEGGIN';
export const GET_CATALOG_DATA_SUCCESS = 'GET_CATALOG_DATA_SUCCESS';

export const SORT_CATALOG = 'SORT_CATALOG';

export const GET_CART_BEGGIN = 'GET_CART_BEGGIN';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';

export const UPDATE_TOTAL = 'UPDATE_TOTAL';

export const SHOW_CHECKOUT_ALERT = 'SHOW_CHECKOUT_ALERT';
export const CLOSE_CHECKOUT_ALERT = 'CLOSE_CHECKOUT_ALERT';
export const CLEAN_CART = 'CLEAN_CART';
export const UPDATE_CART = 'UPDATE_CART';

